version = 0.1

[default.deploy.parameters]
stack_name = "${artifactIdCapitalized}LambdaStack"
resolve_s3 = true
s3_prefix = "${artifactIdCapitalized}Lambda"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
